_wandb:
    value:
        cli_version: 0.18.1
        m:
            - "1": test/accs_d
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Iter step
              "6": []
              "7": []
            - "1": valid/best_acc_b
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/best_acc_d
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/accs_d
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/best_acc_b
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/best_acc_d
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 2
                - 7
                - 13
                - 15
                - 23
                - 55
            "4": 3.9.0
            "5": 0.18.1
            "6": 4.40.0.dev0
            "8":
                - 6
            "12": 0.18.1
            "13": linux-x86_64
