wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726637938
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 7
      - 13
      - 15
      - 23
      4: 3.9.0
      5: 0.17.0
      6: 4.40.0.dev0
      8:
      - 6
      13: linux-x86_64
    m:
    - 1: Iter step
    - 1: valid/accs_d
      5: 1
      6:
      - 1
    - 1: test/accs_d
      5: 1
      6:
      - 1
    - 1: valid/best_acc_b
      5: 1
      6:
      - 1
    - 1: valid/best_acc_d
      5: 1
      6:
      - 1
    - 1: test/best_acc_b
      5: 1
      6:
      - 1
    - 1: test/best_acc_d
      5: 1
      6:
      - 1
